# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
exclude: '^README.rst$|^tests/|^setup.py$|^examples/|^docs/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 5df1a4bf6f04a1ed3a643167b38d502575e29aef
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
    -   id: pylint
        files: ^pipen/.+$
        pass_filenames: false
        types: [python]
        args: [pipen]
-   repo: local
    hooks:
    -   id: create_setuppy
        name: Create setup.py from pyproject.toml
        language: system
        pass_filenames: false
        files: pyproject.toml
        entry: bash -c
        args: ['curl -fsSL https://raw.githubusercontent.com/sdss/flicamera/main/create_setup.py | python']
