FROM justold/immunopipe-base:latest AS builder

COPY --chown=$MAMBA_USER:$MAMBA_USER ./docker /immunopipe/docker

ARG MAMBA_DOCKERFILE_ACTIVATE=1

RUN micromamba env update -n base -f /immunopipe/docker/environment_rpkgs.yml && \
    micromamba clean --all --yes

ENTRYPOINT [ "/usr/local/bin/_entrypoint.sh" ]
