site_name: immunopipe
edit_uri: blob/dev/docs/
repo_url: https://github.com/pwwang/immunopipe
repo_name: pwwang/immunopipe
theme:
    name: 'rtd'
    logo: 'rtd-logo.png'
markdown_extensions:
    - attr_list
    - pymdownx.blocks.admonition
    - pymdownx.blocks.details
    - pymdownx.blocks.tab:
        alternate_style: true
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
        permalink: true
plugins:
    - search # necessary for search to work
    - mike
extra_css:
    - assets/style.css
extra_javascript:
    - assets/script.js
nav:
    - 'Home': 'index.md'
    - 'Introduction': 'introduction.md'
    - 'Installation': 'installation.md'
    - 'Geting started': 'getting-started.md'
    - 'Gallery': 'gallery.md'
    - 'Running the pipeline': 'running.md'
    - 'Preparing the input': 'preparing-input.md'
    - 'Configurations': 'configurations.md'
    - 'Processes':
      - 'SampleInfo': 'processes/SampleInfo.md'
      # scRNA-seq processes
      - 'SeuratPreparing': 'processes/SeuratPreparing.md'
      - 'SeuratClusteringOfAllCells': 'processes/SeuratClusteringOfAllCells.md'
      - 'ClusterMarkersOfAllCells': 'processes/ClusterMarkersOfAllCells.md'
      - 'TopExpressingGenesOfAllCells': 'processes/TopExpressingGenesOfAllCells.md'
      - 'TCellSelection': 'processes/TCellSelection.md'
      - 'ModuleScoreCalculator': 'processes/ModuleScoreCalculator.md'
      - 'SeuratClustering': 'processes/SeuratClustering.md'
      - 'CellTypeAnnotation': 'processes/CellTypeAnnotation.md'
      - 'SeuratMap2Ref': 'processes/SeuratMap2Ref.md'
      - 'ClusterMarkers': 'processes/ClusterMarkers.md'
      - 'TopExpressingGenes': 'processes/TopExpressingGenes.md'
      - 'SeuratSubClustering': 'processes/SeuratSubClustering.md'
      # ScTCR-seq processes
      - 'ScRepLoading': 'processes/ScRepLoading.md'
      - 'ScRepCombiningExpression': 'processes/ScRepCombiningExpression.md'
      - 'TCRClustering': 'processes/TCRClustering.md'
      - 'TESSA': 'processes/TESSA.md'
      # Downstream processes
      - 'SeuratClusterStats': 'processes/SeuratClusterStats.md'
      - 'ScFGSEA': 'processes/ScFGSEA.md'
      - 'MarkersFinder': 'processes/MarkersFinder.md'
      - 'PseudoBulkDEG': 'processes/PseudoBulkDEG.md'
      - 'ClonalStats': 'processes/ClonalStats.md'
      - 'CDR3AAPhyschem': 'processes/CDR3AAPhyschem.md'
      - 'CellCellCommunication': 'processes/CellCellCommunication.md'
      - 'CellCellCommunicationPlots': 'processes/CellCellCommunicationPlots.md'
    - 'Metabolic Landscape Analysis':
      - 'Introduction & Group Arguments': 'processes/ScrnaMetabolicLandscape.md'
      - 'MetabolicInput': 'processes/MetabolicInput.md'
      - 'MetabolicExprImpution': 'processes/MetabolicExprImpution.md'
      - 'MetabolicFeatures': 'processes/MetabolicFeatures.md'
      - 'MetabolicPathwayActivity': 'processes/MetabolicPathwayActivity.md'
      - 'MetabolicPathwayHeterogeneity': 'processes/MetabolicPathwayHeterogeneity.md'
    - 'FAQ': 'faq.md'
    - 'Change log': 'CHANGELOG.md'
