site_name: immunopipe
edit_uri: blob/dev/docs/
repo_url: https://github.com/pwwang/immunopipe
repo_name: pwwang/immunopipe
theme:
    name: 'readthedocs'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
        permalink: true
plugins:
    - search # necessary for search to work
extra_css:
    - style.css
nav:
    - 'Home': 'index.md'
    - 'Introduction': 'introduction.md'
    - 'Installation': 'installation.md'
    - 'Running the pipeline': 'running.md'
    - 'Preparing the input': 'preparing-input.md'
    - 'Configurations': 'configurations.md'
    - 'Processes':
      - 'SampleInfo': 'processes/SampleInfo.md'
      - 'SeuratPreparing': 'processes/SeuratPreparing.md'
      - 'SeuratClusteringOfAllCells': 'processes/SeuratClusteringOfAllCells.md'
      - 'MarkersForClustersOfAllCells': 'processes/MarkersForClustersOfAllCells.md'
      - 'TCellSelection': 'processes/TCellSelection.md'
      - 'SeuratClusteringOfTCells': 'processes/SeuratClusteringOfTCells.md'
      - 'CellTypeAnnotation': 'processes/CellTypeAnnotation.md'
      - 'ImmunarchLoading': 'processes/ImmunarchLoading.md'
      - 'ScFGSEA': 'processes/ScFGSEA.md'
      - 'ScrnaMetabolicLandscape': 'processes/ScrnaMetabolicLandscape.md'
      - 'SeuratClusterStats': 'processes/SeuratClusterStats.md'
      - 'TCRClusters2Seurat': 'processes/TCRClusters2Seurat.md'
      - 'CDR3AAPhyschem': 'processes/CDR3AAPhyschem.md'
      - 'CellsDistribution': 'processes/CellsDistribution.md'
      - 'CloneHeterogeneity': 'processes/CloneHeterogeneity.md'
      - 'CloneResidency': 'processes/CloneResidency.md'
      - 'Immunarch': 'processes/Immunarch.md'
      - 'Immunarch2VDJtools': 'processes/Immunarch2VDJtools.md'
      - 'MarkersFinder': 'processes/MarkersFinder.md'
      - 'MarkersForClustersOfTCells': 'processes/MarkersForClustersOfTCells.md'
      - 'MarkersOverlapping': 'processes/MarkersOverlapping.md'
      - 'MetaMarkers': 'processes/MetaMarkers.md'
      - 'MetabolicExprImpution': 'processes/MetabolicExprImpution.md'
      - 'MetabolicFeatures': 'processes/MetabolicFeatures.md'
      - 'MetabolicFeaturesIntraSubsets': 'processes/MetabolicFeaturesIntraSubsets.md'
      - 'MetabolicLandscape': 'processes/MetabolicLandscape.md'
      - 'MetabolicPathwayActivity': 'processes/MetabolicPathwayActivity.md'
      - 'MetabolicPathwayHeterogeneity': 'processes/MetabolicPathwayHeterogeneity.md'
      - 'RadarPlots': 'processes/RadarPlots.md'
      - 'SeuratMetadataMutater': 'processes/SeuratMetadataMutater.md'
      - 'TCRClustering': 'processes/TCRClustering.md'
      - 'TCRClusteringStats': 'processes/TCRClusteringStats.md'
      - 'TopExpressingGenesOfAllCells': 'processes/TopExpressingGenesOfAllCells.md'
      - 'TopExpressingGenesOfTCells': 'processes/TopExpressingGenesOfTCells.md'
      - 'VJUsage': 'processes/VJUsage.md'
    - 'Change log': 'CHANGELOG.md'
