channels:
  - pwwang  # r-ggradar, r-seuratwrappers
  - conda-forge
  - r
  - bioconda
  - nodefaults
dependencies:
  - nodejs=20  # pipen-report
  - python=3.10
  - curl  # force using conda-forge version
  - pip
  - fontconfig
  - graphviz  # pipen-diagram
  - git  # for copier, used by pipen-report
  - libiconv # fix git: error while loading shared libraries: libiconv.so.2
  - time  # for pipen-runinfo
  - wget
  - gcc_linux-64
  - r-base=4.3
  - pwwang::bioconductor-data-packages
  - bioconductor-fgsea
  - bioconductor-scater
  - bioconductor-destiny
  - bioconductor-glmgampoi
  - bioconductor-destiny  # ModuleScoreCalculator (diffusion map)
  - bioconda::bioconductor-deseq2
  - bioconda::bioconductor-edger
  - r-hdf5r  # Read_10x_h5() by Seurat
  - r-laplacesdemon  # TESSA
  - libgdal
  - r-logger
  - r-presto  # MarkersFinder
  - r-hash  # CDR3AAPhyschem
  - r-glmnet  # CDR3AAPhyschem
  - r-matrixstats=1.1.0  # useNames = NA  deprecated
  - r-broom.mixed  # CDR3AAPhyschem
  - r-hitype
  - r-seuratwrappers
  - r-harmony
  - r-future
  - r-biopipen.utils
  - pip:
    - liana
