channels:
  - aroth85  # vdjtools
  - pwwang  # r-ggradar, r-seuratwrappers
  # - svalkiers
  - conda-forge
  - r
  - bioconda
  - nodefaults
dependencies:
  - nodejs  # pipen-report
  - curl=7.86  # force using conda-forge version
  - python=3.9
  - openjdk=8  # vdjtools
  - vdjtools=1.1.4
  - bioconductor-fgsea
  - bioconductor-scater
  - bioconductor-complexheatmap
  - r-ggradar
  - r-seuratwrappers
  - r-base=4.2.0
  - r-seurat=4.3.0
  - r-future
  - r-tidyseurat
  - r-bracer
  - r-immunarch=0.8.0
  - r-ggplot2
  - r-dplyr
  - r-tibble
  - r-tidyr
  - r-ggprism
  - r-ggvenndiagram
  - r-assertthat
  - r-enrichr
  - pip
  - pip:
    - pydantic==1.10.6
