name: Build Docs (relaese)

# on release only
on: [release]

jobs:
  docs:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install --with docs -v
      - name: Build process reference
        run: make api
      - name: Update docs
        run: |
          python -m pip install -r docs/requirements.txt
          cp README.md docs/index.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          mike deploy --push --update-aliases --allow-empty ${{ github.ref_name }} latest
        if: success()
